### ISSUE TITLE
helical lattice software issue 

### ISSUE THREAD

**Issue by DmitrySemchonok** [jianglab/HelicalLattice#1]
Dear Sir/Madam,

I have an issue running the Helical Lattice software from the website  - https://jiang.bio.purdue.edu/HelicalLattice/
Both links to the websites don't work.

https://helical-lattice.streamlitapp.com/

https://jianglab.github.io/HelicalLattice

Could you please prompt me on how to use this nice software?

Thank you in advance.

Sincerely,
Dmitry

**Comment by wjiang** [comment]
https://helical-lattice.streamlitapp.com is up again

**Comment by DmitrySemchonok** [comment]
Many thanks!

Sincerely,
Dmitry
________________________________
